language: minimal

addons:
  apt:
    packages:
    - luarocks

install: luarocks install --local luacheck
before_script:
script:
   - curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | WOWI_API_TOKEN= GITHUB_OAUTH= bash -s -- -g wrath 
   - curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | WOWI_API_TOKEN= GITHUB_OAUTH= bash -s -- -g classic
   - curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash

notifications:
  email:
    on_success: never
    on_failure: always